### ISSUE TITLE
Runtime should be "Execution Engine"

### ISSUE THREAD

**Issue by strangiato** [RedHatQuickCourses/rhoai-pipelines-v2#18]
In the introduction to KFP:

https://github.com/RedHatQuickCourses/rhoai-pipelines-v2/blob/84ba0edc7f0aeed77afeed22e85b99a8f2dbeea4/modules/chapter4/pages/index.adoc

The document says:

```
OpenShift AI uses the Argo Workflows runtime to execute pipelines
```

Argo Workflows is an "execution engine" not a runtime.

A runtime is the image that a task in the pipeline uses to run that task.  Runtimes are user definable in the pipeline definition.

**Comment by kknoxrht** [comment]
Updated !  thank you taking the time to send this over.
